name: music_player
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  audio_video_progress_bar: ^2.0.3
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.8
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  flutter:
    sdk: flutter
  icons_launcher: ^3.0.1
  just_audio: ^0.9.46
  provider: ^6.1.2
  shimmer: ^3.0.0
  youtube_explode_dart: ^2.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
icons_launcher:
  image_path: "assets/images/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
